### ISSUE TITLE
Item frame holo names doesn't seem to work on MC: 1.16.5

### ISSUE THREAD

**Issue by Kenaestic** [ProfliXx/HoloDropsX#7]
Enabling or disabling the option has no effect. I'm using spigot on the newest version and everything else is up to date.

Config file:
https://pastebin.pl/view/e8a89e7a

**Comment by ProfliXx** [comment]
partying_face Fixed in v2.2.0 update! partying_face

**Comment by Kenaestic** [comment]
It seems to only fix old items on item frames. When I put a new item in it still doesn't work :/
